// GENERATED by scripts/gen-authz.mjs from the project's OpenAPI contracts
// (specs/design/components/*/openapi.yaml and
// specs/design/components/*/dependencies/*.openapi.yaml).
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after a contract changes. COMMIT this file: the
// per-component image build cannot see the specs tree.
//
// This table is what a screen is gated on. src/authz/screens.ts names the
// operation each screen LOADS; holding that operation's scope is what makes the
// screen reachable. Nothing else in the app decides that.

import type { Scope } from "./roles.gen";

/** What the gateway demands of a caller before it will pass an operation on. */
export type OperationRequirement =
  | { readonly kind: "public" }
  | { readonly kind: "signedIn" }
  | { readonly kind: "scope"; readonly scope: Scope };

/** "<METHOD> <path template>" as the contract spells it, e.g. "GET /me/claims". Sorted. */
export type OperationKey =
  | "DELETE /me/meal-plan/{entryId}"
  | "DELETE /me/recipes/{recipeId}"
  | "GET /me/meal-plan"
  | "GET /me/recipes"
  | "GET /me/recipes/{recipeId}"
  | "GET /me/shopping-list"
  | "PATCH /me/shopping-list/{itemId}"
  | "POST /me/meal-plan"
  | "POST /me/recipes"
  | "POST /me/shopping-list/generate"
  | "PUT /me/recipes/{recipeId}"
  | "PUT /me/recipes/{recipeId}/photo";

export const OPERATIONS: Record<OperationKey, OperationRequirement> = {
  "DELETE /me/meal-plan/{entryId}": { kind: "scope", scope: "meal-plan:manage" },
  "DELETE /me/recipes/{recipeId}": { kind: "scope", scope: "recipes:delete" },
  "GET /me/meal-plan": { kind: "scope", scope: "meal-plan:read" },
  "GET /me/recipes": { kind: "scope", scope: "recipes:read" },
  "GET /me/recipes/{recipeId}": { kind: "scope", scope: "recipes:read" },
  "GET /me/shopping-list": { kind: "scope", scope: "shopping-list:read" },
  "PATCH /me/shopping-list/{itemId}": { kind: "scope", scope: "shopping-list:update" },
  "POST /me/meal-plan": { kind: "scope", scope: "meal-plan:manage" },
  "POST /me/recipes": { kind: "scope", scope: "recipes:create" },
  "POST /me/shopping-list/generate": { kind: "scope", scope: "shopping-list:update" },
  "PUT /me/recipes/{recipeId}": { kind: "scope", scope: "recipes:update" },
  "PUT /me/recipes/{recipeId}/photo": { kind: "scope", scope: "recipes:update" },
};

export function isOperationKey(value: string): value is OperationKey {
  return Object.prototype.hasOwnProperty.call(OPERATIONS, value);
}
